//! Nav panel button and item types.

use std::borrow::Cow;

// ── Submenu item ─────────────────────────────────────────────────────────────

/// An item in a button's flyout submenu.
///
/// Text fields (`id`, `label`, `icon`, `shortcut`) are `Cow<'static, str>` so
/// they accept both compile-time string literals (zero-cost) and runtime
/// strings (loaded from JSON, generated by plugins, localised). Constructors
/// take `impl Into<Cow<'static, str>>` — `&'static str` and `String` both
/// work transparently.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub enum SubMenuItem {
    /// Clickable item.
    Item {
        id: Cow<'static, str>,
        label: Cow<'static, str>,
        icon: Option<Cow<'static, str>>,
        shortcut: Option<Cow<'static, str>>,
    },
    /// Visual separator line between items.
    Separator,
}

impl SubMenuItem {
    pub fn new(id: impl Into<Cow<'static, str>>, label: impl Into<Cow<'static, str>>) -> Self {
        Self::Item {
            id: id.into(),
            label: label.into(),
            icon: None,
            shortcut: None,
        }
    }
    pub fn with_icon(self, icon: impl Into<Cow<'static, str>>) -> Self {
        match self {
            Self::Item {
                id,
                label,
                shortcut,
                ..
            } => Self::Item {
                id,
                label,
                icon: Some(icon.into()),
                shortcut,
            },
            s => s,
        }
    }
    pub fn with_shortcut(self, sc: impl Into<Cow<'static, str>>) -> Self {
        match self {
            Self::Item {
                id, label, icon, ..
            } => Self::Item {
                id,
                label,
                icon,
                shortcut: Some(sc.into()),
            },
            s => s,
        }
    }
    pub fn separator() -> Self {
        Self::Separator
    }
}

// ── Nav button ───────────────────────────────────────────────────────────────

/// A button in the navigation panel.
///
/// All text fields are `Cow<'static, str>` — string literals are borrowed
/// (zero-cost), runtime strings are stored owned. Constructors accept
/// either flavour via `impl Into<Cow<'static, str>>`.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct NavButton {
    pub id: Cow<'static, str>,
    pub icon: Cow<'static, str>,
    pub tooltip: String,
    pub color: Option<[f32; 4]>,
    pub submenu: Vec<SubMenuItem>,
    pub badge: Option<String>,
    /// Show tooltip on hover. Default: `true`.
    pub show_tooltip: bool,
}

impl NavButton {
    pub fn action(
        id: impl Into<Cow<'static, str>>,
        icon: impl Into<Cow<'static, str>>,
        tooltip: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            icon: icon.into(),
            tooltip: tooltip.into(),
            color: None,
            submenu: Vec::new(),
            badge: None,
            show_tooltip: true,
        }
    }
    pub fn submenu(
        id: impl Into<Cow<'static, str>>,
        icon: impl Into<Cow<'static, str>>,
        tooltip: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            icon: icon.into(),
            tooltip: tooltip.into(),
            color: None,
            submenu: Vec::new(),
            badge: None,
            show_tooltip: true,
        }
    }
    pub fn with_color(mut self, c: [f32; 4]) -> Self {
        self.color = Some(c);
        self
    }
    pub fn add_item(mut self, item: SubMenuItem) -> Self {
        self.submenu.push(item);
        self
    }
    pub fn add_separator(mut self) -> Self {
        self.submenu.push(SubMenuItem::Separator);
        self
    }
    pub fn without_tooltip(mut self) -> Self {
        self.show_tooltip = false;
        self
    }
    pub fn with_badge(mut self, text: impl Into<String>) -> Self {
        self.badge = Some(text.into());
        self
    }
    /// Builder: update the tooltip (useful when rebuilding the config each
    /// frame with freshly localised strings).
    pub fn with_tooltip(mut self, tooltip: impl Into<String>) -> Self {
        self.tooltip = tooltip.into();
        self
    }
}

// ── Nav panel item ───────────────────────────────────────────────────────────

/// An element in the navigation panel layout.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub enum NavItem {
    Button(NavButton),
    Separator,
}
