//! Material Design Icons (MDI) integration for Dear ImGui.
//!
//! Font: materialdesignicons-webfont.ttf (v7.4)
//! Total icons: 7447 (auto-generated)
//! Browse all icons: https://pictogrammers.com/library/mdi/
//!
//! Generated by: scripts/generate_mdi_icons.py

#![allow(missing_docs)] // TODO: per-module doc-coverage pass — see CONTRIBUTING.md
// ─── Icon codepoint constants ────────────────────────────────────────────────
//
// Usage:  ui.text(icons::CLOSE);
//         draw.add_text(pos, color, icons::WINDOW_CLOSE);

// Chunked icon constant modules
// (each `cNN` module holds a slice of the auto-generated icon constants,
// re-exported here so `crate::icons::MDI_FOO` paths remain unchanged)
mod c00;
pub use c00::*;
mod c01;
pub use c01::*;
mod c02;
pub use c02::*;
mod c03;
pub use c03::*;
mod c04;
pub use c04::*;
mod c05;
pub use c05::*;
mod c06;
pub use c06::*;
mod c07;
pub use c07::*;
mod c08;
pub use c08::*;
mod c09;
pub use c09::*;
mod c10;
pub use c10::*;
mod c11;
pub use c11::*;
mod c12;
pub use c12::*;
mod c13;
pub use c13::*;
mod c14;
pub use c14::*;
mod c15;
pub use c15::*;
mod c16;
pub use c16::*;

// ── Backward-compatible aliases ──
/// Alias for `CODE_JSON` (pre-v1.7 name).
pub const JSON: &str = CODE_JSON;
