//! RON formatter + parser for [`FlatExportData`] / [`TreeExportNode`].

use super::{FieldValue, FlatExportData, TreeExportNode};

// ── Formatter ────────────────────────────────────────────────────────────────

fn field_value_ron(v: &FieldValue) -> String {
    match v {
        FieldValue::Null => "None".into(),
        FieldValue::Bool(b) => b.to_string(),
        FieldValue::Int(i) => i.to_string(),
        FieldValue::Float(f) => format!("{}", f),
        FieldValue::Str(s) => format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\"")),
        FieldValue::Color(c) => format!("({:.3}, {:.3}, {:.3}, {:.3})", c[0], c[1], c[2], c[3]),
    }
}

pub(super) fn format_flat(data: &FlatExportData) -> String {
    let mut out = String::from("[\n");
    for (ri, row) in data.rows.iter().enumerate() {
        out.push_str("  (");
        for (ci, val) in row.iter().enumerate() {
            if ci > 0 {
                out.push_str(", ");
            }
            let key = data.columns.get(ci).map(|s| s.as_str()).unwrap_or("?");
            out.push_str(&format!("{}: {}", key, field_value_ron(val)));
        }
        out.push(')');
        if ri + 1 < data.rows.len() {
            out.push(',');
        }
        out.push('\n');
    }
    out.push(']');
    out
}

pub(super) fn format_tree(nodes: &[TreeExportNode], indent: usize) -> String {
    let pad = "  ".repeat(indent);
    let mut out = String::from("[\n");
    for (i, node) in nodes.iter().enumerate() {
        out.push_str(&format!("{}  (\n", pad));
        for (key, val) in &node.fields {
            out.push_str(&format!("{}    {}: {},\n", pad, key, field_value_ron(val)));
        }
        if !node.children.is_empty() {
            out.push_str(&format!(
                "{}    children: {},\n",
                pad,
                format_tree(&node.children, indent + 2)
            ));
        }
        out.push_str(&format!("{}  )", pad));
        if i + 1 < nodes.len() {
            out.push(',');
        }
        out.push('\n');
    }
    out.push_str(&format!("{}]", pad));
    out
}

// ── Parser ───────────────────────────────────────────────────────────────────

/// Parse a RON list-of-tuples into flat data.
///
/// Supports the subset generated by [`format_flat`]:
/// ```ron
/// [
///   (name: "Alice", age: 30, active: true),
///   (name: "Bob", age: 25, active: false),
/// ]
/// ```
pub(super) fn parse_flat(content: &str) -> Option<FlatExportData> {
    let content = content.trim();
    if !content.starts_with('[') || !content.ends_with(']') {
        return None;
    }
    let inner = &content[1..content.len() - 1];

    let mut columns = Vec::new();
    let mut col_set = std::collections::HashSet::new();
    let mut rows = Vec::new();

    // Split RON tuples delimited by ( ... ).
    for tuple_str in split_ron_tuples(inner) {
        let fields = parse_ron_tuple(tuple_str.trim());
        if rows.is_empty() {
            for (key, _) in &fields {
                if col_set.insert(key.clone()) {
                    columns.push(key.clone());
                }
            }
        }
        rows.push(fields);
    }

    if columns.is_empty() {
        return None;
    }

    let mut data = FlatExportData::new(columns.clone());
    for fields in &rows {
        let mut row = vec![FieldValue::Null; columns.len()];
        for (key, val) in fields {
            if let Some(idx) = columns.iter().position(|c| c == key) {
                row[idx] = val.clone();
            }
        }
        data.add_row(row);
    }

    Some(data)
}

fn split_ron_tuples(s: &str) -> Vec<&str> {
    let mut results = Vec::new();
    let mut depth = 0i32;
    let mut start = None;
    let bytes = s.as_bytes();
    let mut in_string = false;
    let mut escape = false;

    for (i, &b) in bytes.iter().enumerate() {
        if escape {
            escape = false;
            continue;
        }
        if b == b'\\' && in_string {
            escape = true;
            continue;
        }
        if b == b'"' {
            in_string = !in_string;
            continue;
        }
        if in_string {
            continue;
        }

        if b == b'(' {
            if depth == 0 {
                start = Some(i);
            }
            depth += 1;
        } else if b == b')' {
            depth -= 1;
            if depth == 0 {
                if let Some(s_idx) = start {
                    results.push(&s[s_idx..=i]);
                }
                start = None;
            }
        }
    }
    results
}

fn parse_ron_tuple(s: &str) -> Vec<(String, FieldValue)> {
    let s = s.trim();
    if !s.starts_with('(') || !s.ends_with(')') {
        return Vec::new();
    }
    let inner = s[1..s.len() - 1].trim();
    if inner.is_empty() {
        return Vec::new();
    }

    let mut fields = Vec::new();
    let mut remaining = inner;

    while !remaining.is_empty() {
        remaining = remaining.trim_start_matches([',', ' ', '\n', '\r', '\t']);
        if remaining.is_empty() {
            break;
        }

        // Parse key (unquoted identifier).
        let colon_pos = match remaining.find(':') {
            Some(p) => p,
            None => break,
        };
        let key = remaining[..colon_pos].trim().to_string();
        remaining = remaining[colon_pos + 1..].trim();

        // Parse value.
        let (val, rest) = parse_ron_value(remaining);
        fields.push((key, val));
        remaining = rest.trim_start_matches([',', ' ', '\n', '\r', '\t']);
    }

    fields
}

fn parse_ron_value(s: &str) -> (FieldValue, &str) {
    let s = s.trim();
    if let Some(rest) = s.strip_prefix('"') {
        // String. `close` is the byte index of the terminating quote, or
        // `None` when unterminated (malformed input) — consume the rest
        // in that case instead of slicing at byte 1, which could split a
        // multi-byte UTF-8 char and panic.
        //
        // Only `\\` and `\"` are emitted by the formatter, so the
        // two-pass `replace` is order-safe (unlike JSON, there is no
        // two-char `\n`/`\t` escape to collide with a doubled backslash).
        let mut close: Option<usize> = None;
        let mut escape = false;
        for (i, b) in rest.bytes().enumerate() {
            if escape {
                escape = false;
                continue;
            }
            if b == b'\\' {
                escape = true;
                continue;
            }
            if b == b'"' {
                close = Some(i);
                break;
            }
        }
        let (raw, rem) = match close {
            Some(end) => (&rest[..end], &rest[end + 1..]),
            None => (rest, ""),
        };
        // Quote-unescape before backslash-unescape: the formatter only
        // doubles `\` and escapes `"`, so this order round-trips every
        // combination (verified against `\`, `"`, `\"`, `\\"` etc.).
        let val = raw.replace("\\\"", "\"").replace("\\\\", "\\");
        (FieldValue::Str(val), rem)
    } else if let Some(rest) = s.strip_prefix("None") {
        (FieldValue::Null, rest)
    } else if let Some(rest) = s.strip_prefix("true") {
        (FieldValue::Bool(true), rest)
    } else if let Some(rest) = s.strip_prefix("false") {
        (FieldValue::Bool(false), rest)
    } else if let Some(body) = s.strip_prefix('(') {
        // Color tuple (r, g, b, a). When the `)` is missing (malformed
        // input) treat the rest of the slice as the tuple body and leave
        // no remainder — `s.len()` for the close index would make
        // `close + 1` index past the end and panic.
        let (inner, after) = match body.find(')') {
            Some(close) => (&body[..close], &body[close + 1..]),
            None => (body, ""),
        };
        let nums: Vec<f32> = inner
            .split(',')
            .filter_map(|n| n.trim().parse::<f32>().ok())
            .collect();
        if nums.len() == 4 {
            (
                FieldValue::Color([nums[0], nums[1], nums[2], nums[3]]),
                after,
            )
        } else {
            // Not a 4-tuple colour — surface the raw text up to (and
            // including, when present) the closing paren as a string.
            let raw_end = s.len() - after.len();
            (FieldValue::Str(s[..raw_end].to_string()), after)
        }
    } else {
        // Number.
        let end = s.find([',', ')', '\n', ' ']).unwrap_or(s.len());
        let num_str = s[..end].trim();
        if num_str.contains('.') || num_str.contains('e') || num_str.contains('E') {
            let f = num_str.parse::<f64>().unwrap_or(0.0);
            (FieldValue::Float(f), &s[end..])
        } else {
            let i = num_str.parse::<i64>().unwrap_or(0);
            (FieldValue::Int(i), &s[end..])
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn round_trip_str(s: &str) -> String {
        let mut d = FlatExportData::new(vec!["v".into()]);
        d.add_row(vec![FieldValue::Str(s.into())]);
        let ron = format_flat(&d);
        let parsed = parse_flat(&ron).expect("parse");
        match &parsed.rows[0][0] {
            FieldValue::Str(out) => out.clone(),
            other => panic!("expected Str, got {other:?}"),
        }
    }

    #[test]
    fn escaping_round_trips() {
        // RON only escapes `\` and `"`; the two-pass unescape must be
        // order-safe across every backslash/quote combination.
        assert_eq!(round_trip_str("plain"), "plain");
        assert_eq!(round_trip_str("a\\b"), "a\\b");
        assert_eq!(round_trip_str("a\"b"), "a\"b");
        assert_eq!(round_trip_str("a\\\"b"), "a\\\"b");
        assert_eq!(round_trip_str("back\\slash"), "back\\slash");
        assert_eq!(round_trip_str("trailing\\"), "trailing\\");
    }

    #[test]
    fn parse_unterminated_string_does_not_panic() {
        // Multi-byte first char + missing closing quote: must consume the
        // remainder instead of slicing mid-codepoint.
        let (val, rest) = parse_ron_value("\"\u{00e9}abc");
        assert_eq!(rest, "");
        match val {
            FieldValue::Str(s) => assert_eq!(s, "\u{00e9}abc"),
            other => panic!("expected Str, got {other:?}"),
        }
    }

    #[test]
    fn parse_unterminated_color_tuple_does_not_panic() {
        // Regression: missing `)` set `close == s.len()`, and `&s[close + 1..]`
        // indexed past the end and panicked.
        let (_val, rest) = parse_ron_value("(0.1, 0.2, 0.3");
        assert_eq!(rest, "");
    }

    #[test]
    fn color_tuple_round_trips() {
        let mut d = FlatExportData::new(vec!["c".into()]);
        d.add_row(vec![FieldValue::Color([0.25, 0.5, 0.75, 1.0])]);
        let ron = format_flat(&d);
        let parsed = parse_flat(&ron).unwrap();
        match &parsed.rows[0][0] {
            FieldValue::Color(c) => {
                assert!((c[0] - 0.25).abs() < 1e-3);
                assert!((c[2] - 0.75).abs() < 1e-3);
            }
            other => panic!("expected Color, got {other:?}"),
        }
    }

    #[test]
    fn none_parses_as_null() {
        let parsed = parse_flat("[\n  (x: None),\n]").unwrap();
        assert!(matches!(parsed.rows[0][0], FieldValue::Null));
    }
}
