//! RON formatter + parser for [`FlatExportData`] / [`TreeExportNode`].

use super::{FieldValue, FlatExportData, TreeExportNode};

// ── Formatter ────────────────────────────────────────────────────────────────

fn field_value_ron(v: &FieldValue) -> String {
    match v {
        FieldValue::Null => "None".into(),
        FieldValue::Bool(b) => b.to_string(),
        FieldValue::Int(i) => i.to_string(),
        FieldValue::Float(f) => format!("{}", f),
        FieldValue::Str(s) => format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\"")),
        FieldValue::Color(c) => format!("({:.3}, {:.3}, {:.3}, {:.3})", c[0], c[1], c[2], c[3]),
    }
}

pub(super) fn format_flat(data: &FlatExportData) -> String {
    let mut out = String::from("[\n");
    for (ri, row) in data.rows.iter().enumerate() {
        out.push_str("  (");
        for (ci, val) in row.iter().enumerate() {
            if ci > 0 {
                out.push_str(", ");
            }
            let key = data.columns.get(ci).map(|s| s.as_str()).unwrap_or("?");
            out.push_str(&format!("{}: {}", key, field_value_ron(val)));
        }
        out.push(')');
        if ri + 1 < data.rows.len() {
            out.push(',');
        }
        out.push('\n');
    }
    out.push(']');
    out
}

pub(super) fn format_tree(nodes: &[TreeExportNode], indent: usize) -> String {
    let pad = "  ".repeat(indent);
    let mut out = String::from("[\n");
    for (i, node) in nodes.iter().enumerate() {
        out.push_str(&format!("{}  (\n", pad));
        for (key, val) in &node.fields {
            out.push_str(&format!("{}    {}: {},\n", pad, key, field_value_ron(val)));
        }
        if !node.children.is_empty() {
            out.push_str(&format!(
                "{}    children: {},\n",
                pad,
                format_tree(&node.children, indent + 2)
            ));
        }
        out.push_str(&format!("{}  )", pad));
        if i + 1 < nodes.len() {
            out.push(',');
        }
        out.push('\n');
    }
    out.push_str(&format!("{}]", pad));
    out
}

// ── Parser ───────────────────────────────────────────────────────────────────

/// Parse a RON list-of-tuples into flat data.
///
/// Supports the subset generated by [`format_flat`]:
/// ```ron
/// [
///   (name: "Alice", age: 30, active: true),
///   (name: "Bob", age: 25, active: false),
/// ]
/// ```
pub(super) fn parse_flat(content: &str) -> Option<FlatExportData> {
    let content = content.trim();
    if !content.starts_with('[') || !content.ends_with(']') {
        return None;
    }
    let inner = &content[1..content.len() - 1];

    let mut columns = Vec::new();
    let mut col_set = std::collections::HashSet::new();
    let mut rows = Vec::new();

    // Split RON tuples delimited by ( ... ).
    for tuple_str in split_ron_tuples(inner) {
        let fields = parse_ron_tuple(tuple_str.trim());
        if rows.is_empty() {
            for (key, _) in &fields {
                if col_set.insert(key.clone()) {
                    columns.push(key.clone());
                }
            }
        }
        rows.push(fields);
    }

    if columns.is_empty() {
        return None;
    }

    let mut data = FlatExportData::new(columns.clone());
    for fields in &rows {
        let mut row = vec![FieldValue::Null; columns.len()];
        for (key, val) in fields {
            if let Some(idx) = columns.iter().position(|c| c == key) {
                row[idx] = val.clone();
            }
        }
        data.add_row(row);
    }

    Some(data)
}

fn split_ron_tuples(s: &str) -> Vec<&str> {
    let mut results = Vec::new();
    let mut depth = 0i32;
    let mut start = None;
    let bytes = s.as_bytes();
    let mut in_string = false;
    let mut escape = false;

    for (i, &b) in bytes.iter().enumerate() {
        if escape {
            escape = false;
            continue;
        }
        if b == b'\\' && in_string {
            escape = true;
            continue;
        }
        if b == b'"' {
            in_string = !in_string;
            continue;
        }
        if in_string {
            continue;
        }

        if b == b'(' {
            if depth == 0 {
                start = Some(i);
            }
            depth += 1;
        } else if b == b')' {
            depth -= 1;
            if depth == 0 {
                if let Some(s_idx) = start {
                    results.push(&s[s_idx..=i]);
                }
                start = None;
            }
        }
    }
    results
}

fn parse_ron_tuple(s: &str) -> Vec<(String, FieldValue)> {
    let s = s.trim();
    if !s.starts_with('(') || !s.ends_with(')') {
        return Vec::new();
    }
    let inner = s[1..s.len() - 1].trim();
    if inner.is_empty() {
        return Vec::new();
    }

    let mut fields = Vec::new();
    let mut remaining = inner;

    while !remaining.is_empty() {
        remaining = remaining.trim_start_matches([',', ' ', '\n', '\r', '\t']);
        if remaining.is_empty() {
            break;
        }

        // Parse key (unquoted identifier).
        let colon_pos = match remaining.find(':') {
            Some(p) => p,
            None => break,
        };
        let key = remaining[..colon_pos].trim().to_string();
        remaining = remaining[colon_pos + 1..].trim();

        // Parse value.
        let (val, rest) = parse_ron_value(remaining);
        fields.push((key, val));
        remaining = rest.trim_start_matches([',', ' ', '\n', '\r', '\t']);
    }

    fields
}

fn parse_ron_value(s: &str) -> (FieldValue, &str) {
    let s = s.trim();
    if let Some(rest) = s.strip_prefix('"') {
        // String.
        let mut end = 0;
        let mut escape = false;
        for (i, b) in rest.bytes().enumerate() {
            if escape {
                escape = false;
                continue;
            }
            if b == b'\\' {
                escape = true;
                continue;
            }
            if b == b'"' {
                end = i;
                break;
            }
        }
        let val = rest[..end].replace("\\\"", "\"").replace("\\\\", "\\");
        (FieldValue::Str(val), &rest[end + 1..])
    } else if let Some(rest) = s.strip_prefix("None") {
        (FieldValue::Null, rest)
    } else if let Some(rest) = s.strip_prefix("true") {
        (FieldValue::Bool(true), rest)
    } else if let Some(rest) = s.strip_prefix("false") {
        (FieldValue::Bool(false), rest)
    } else if s.starts_with('(') {
        // Color tuple (r, g, b, a).
        let close = s.find(')').unwrap_or(s.len());
        let inner = &s[1..close];
        let nums: Vec<f32> = inner
            .split(',')
            .filter_map(|n| n.trim().parse::<f32>().ok())
            .collect();
        if nums.len() == 4 {
            (
                FieldValue::Color([nums[0], nums[1], nums[2], nums[3]]),
                &s[close + 1..],
            )
        } else {
            (FieldValue::Str(s[..close + 1].to_string()), &s[close + 1..])
        }
    } else {
        // Number.
        let end = s.find([',', ')', '\n', ' ']).unwrap_or(s.len());
        let num_str = s[..end].trim();
        if num_str.contains('.') || num_str.contains('e') || num_str.contains('E') {
            let f = num_str.parse::<f64>().unwrap_or(0.0);
            (FieldValue::Float(f), &s[end..])
        } else {
            let i = num_str.parse::<i64>().unwrap_or(0);
            (FieldValue::Int(i), &s[end..])
        }
    }
}
