//! YAML formatter + parser for [`FlatExportData`] / [`TreeExportNode`].

use super::{FieldValue, FlatExportData, TreeExportNode};

// ── Formatter ────────────────────────────────────────────────────────────────

fn field_value_yaml(v: &FieldValue) -> String {
    match v {
        FieldValue::Null => "~".into(),
        FieldValue::Bool(b) => b.to_string(),
        FieldValue::Int(i) => i.to_string(),
        FieldValue::Float(f) => format!("{}", f),
        FieldValue::Str(s) => {
            if s.contains('\n')
                || s.contains(':')
                || s.contains('#')
                || s.starts_with(' ')
                || s.starts_with('"')
                || s.is_empty()
            {
                format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
            } else {
                s.clone()
            }
        }
        FieldValue::Color(c) => format!("[{:.3}, {:.3}, {:.3}, {:.3}]", c[0], c[1], c[2], c[3]),
    }
}

pub(super) fn format_flat(data: &FlatExportData) -> String {
    let mut out = String::new();
    for row in &data.rows {
        out.push_str("- ");
        for (ci, val) in row.iter().enumerate() {
            let key = data.columns.get(ci).map(|s| s.as_str()).unwrap_or("?");
            if ci == 0 {
                out.push_str(&format!("{}: {}\n", key, field_value_yaml(val)));
            } else {
                out.push_str(&format!("  {}: {}\n", key, field_value_yaml(val)));
            }
        }
    }
    out
}

pub(super) fn format_tree(nodes: &[TreeExportNode], indent: usize) -> String {
    let pad = "  ".repeat(indent);
    let mut out = String::new();
    for node in nodes {
        out.push_str(&format!("{}- ", pad));
        for (fi, (key, val)) in node.fields.iter().enumerate() {
            if fi == 0 {
                out.push_str(&format!("{}: {}\n", key, field_value_yaml(val)));
            } else {
                out.push_str(&format!("{}  {}: {}\n", pad, key, field_value_yaml(val)));
            }
        }
        if !node.children.is_empty() {
            out.push_str(&format!("{}  children:\n", pad));
            out.push_str(&format_tree(&node.children, indent + 2));
        }
    }
    out
}

// ── Parser ───────────────────────────────────────────────────────────────────

/// Parse a YAML list-of-objects into flat data.
///
/// Supports the subset generated by [`format_flat`]:
/// ```yaml
/// - name: Alice
///   age: 30
///   active: true
/// - name: Bob
///   age: 25
/// ```
pub(super) fn parse_flat(content: &str) -> Option<FlatExportData> {
    let mut columns = Vec::new();
    let mut col_set = std::collections::HashSet::new();
    let mut rows: Vec<Vec<(String, FieldValue)>> = Vec::new();
    let mut current_fields: Vec<(String, FieldValue)> = Vec::new();

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        if let Some(rest) = trimmed.strip_prefix("- ") {
            // New list item. Flush previous.
            if !current_fields.is_empty() {
                rows.push(std::mem::take(&mut current_fields));
            }
            // Parse the key: value on the same line as "- ".
            if let Some((key, val)) = parse_yaml_kv(rest) {
                if col_set.insert(key.clone()) {
                    columns.push(key.clone());
                }
                current_fields.push((key, val));
            }
        } else if let Some((key, val)) = parse_yaml_kv(trimmed) {
            // Continuation field of current item.
            if col_set.insert(key.clone()) {
                columns.push(key.clone());
            }
            current_fields.push((key, val));
        }
    }
    // Flush last item.
    if !current_fields.is_empty() {
        rows.push(current_fields);
    }

    if columns.is_empty() {
        return None;
    }

    // Build aligned rows.
    let mut data = FlatExportData::new(columns.clone());
    for fields in &rows {
        let mut row = vec![FieldValue::Null; columns.len()];
        for (key, val) in fields {
            if let Some(idx) = columns.iter().position(|c| c == key) {
                row[idx] = val.clone();
            }
        }
        data.add_row(row);
    }

    Some(data)
}

fn parse_yaml_kv(s: &str) -> Option<(String, FieldValue)> {
    let colon_pos = s.find(':')?;
    let key = s[..colon_pos].trim().to_string();
    let val_str = s[colon_pos + 1..].trim();

    let val = parse_yaml_value(val_str);
    Some((key, val))
}

fn parse_yaml_value(s: &str) -> FieldValue {
    if s.is_empty() || s == "~" || s == "null" {
        return FieldValue::Null;
    }
    if s == "true" {
        return FieldValue::Bool(true);
    }
    if s == "false" {
        return FieldValue::Bool(false);
    }

    // Quoted string.
    if s.starts_with('"') && s.ends_with('"') && s.len() >= 2 {
        let inner = &s[1..s.len() - 1];
        return FieldValue::Str(inner.replace("\\\"", "\"").replace("\\\\", "\\"));
    }

    // Array (color).
    if s.starts_with('[') && s.ends_with(']') {
        let inner = &s[1..s.len() - 1];
        let nums: Vec<f32> = inner
            .split(',')
            .filter_map(|n| n.trim().parse::<f32>().ok())
            .collect();
        if nums.len() == 4 {
            return FieldValue::Color([nums[0], nums[1], nums[2], nums[3]]);
        }
        return FieldValue::Str(s.to_string());
    }

    // Number.
    if let Ok(i) = s.parse::<i64>() {
        return FieldValue::Int(i);
    }
    if let Ok(f) = s.parse::<f64>() {
        return FieldValue::Float(f);
    }

    FieldValue::Str(s.to_string())
}
