//! YAML formatter + parser for [`FlatExportData`] / [`TreeExportNode`].

use super::{FieldValue, FlatExportData, TreeExportNode};

// ── Formatter ────────────────────────────────────────────────────────────────

/// True when a `Str` payload must be double-quoted so the parser reads it
/// back as a string rather than mis-typing it (bool / null / number /
/// array) or breaking the line-oriented scanner.
fn yaml_needs_quotes(s: &str) -> bool {
    if s.is_empty() {
        return true;
    }
    // Structural / indicator characters and leading whitespace that the
    // line parser or `parse_yaml_value` would otherwise misinterpret.
    if s.contains('\n')
        || s.contains(':')
        || s.contains('#')
        || s.starts_with(' ')
        || s.ends_with(' ')
        || s.starts_with('"')
        || s.starts_with('[')
        || s.starts_with([
            '-', '&', '*', '!', '|', '>', '@', '`', '\'', '%', '{', '}', ',',
        ])
    {
        return true;
    }
    // Scalars that would round-trip to a non-string type.
    matches!(s, "true" | "false" | "null" | "~")
        || s.parse::<i64>().is_ok()
        || s.parse::<f64>().is_ok()
}

fn field_value_yaml(v: &FieldValue) -> String {
    match v {
        FieldValue::Null => "~".into(),
        FieldValue::Bool(b) => b.to_string(),
        FieldValue::Int(i) => i.to_string(),
        FieldValue::Float(f) => format!("{}", f),
        FieldValue::Str(s) => {
            if yaml_needs_quotes(s) {
                format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\""))
            } else {
                s.clone()
            }
        }
        FieldValue::Color(c) => format!("[{:.3}, {:.3}, {:.3}, {:.3}]", c[0], c[1], c[2], c[3]),
    }
}

pub(super) fn format_flat(data: &FlatExportData) -> String {
    let mut out = String::new();
    for row in &data.rows {
        out.push_str("- ");
        for (ci, val) in row.iter().enumerate() {
            let key = data.columns.get(ci).map(|s| s.as_str()).unwrap_or("?");
            if ci == 0 {
                out.push_str(&format!("{}: {}\n", key, field_value_yaml(val)));
            } else {
                out.push_str(&format!("  {}: {}\n", key, field_value_yaml(val)));
            }
        }
    }
    out
}

pub(super) fn format_tree(nodes: &[TreeExportNode], indent: usize) -> String {
    let pad = "  ".repeat(indent);
    let mut out = String::new();
    for node in nodes {
        out.push_str(&format!("{}- ", pad));
        for (fi, (key, val)) in node.fields.iter().enumerate() {
            if fi == 0 {
                out.push_str(&format!("{}: {}\n", key, field_value_yaml(val)));
            } else {
                out.push_str(&format!("{}  {}: {}\n", pad, key, field_value_yaml(val)));
            }
        }
        if !node.children.is_empty() {
            out.push_str(&format!("{}  children:\n", pad));
            out.push_str(&format_tree(&node.children, indent + 2));
        }
    }
    out
}

// ── Parser ───────────────────────────────────────────────────────────────────

/// Parse a YAML list-of-objects into flat data.
///
/// Supports the subset generated by [`format_flat`]:
/// ```yaml
/// - name: Alice
///   age: 30
///   active: true
/// - name: Bob
///   age: 25
/// ```
pub(super) fn parse_flat(content: &str) -> Option<FlatExportData> {
    let mut columns = Vec::new();
    let mut col_set = std::collections::HashSet::new();
    let mut rows: Vec<Vec<(String, FieldValue)>> = Vec::new();
    let mut current_fields: Vec<(String, FieldValue)> = Vec::new();

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        if let Some(rest) = trimmed.strip_prefix("- ") {
            // New list item. Flush previous.
            if !current_fields.is_empty() {
                rows.push(std::mem::take(&mut current_fields));
            }
            // Parse the key: value on the same line as "- ".
            if let Some((key, val)) = parse_yaml_kv(rest) {
                if col_set.insert(key.clone()) {
                    columns.push(key.clone());
                }
                current_fields.push((key, val));
            }
        } else if let Some((key, val)) = parse_yaml_kv(trimmed) {
            // Continuation field of current item.
            if col_set.insert(key.clone()) {
                columns.push(key.clone());
            }
            current_fields.push((key, val));
        }
    }
    // Flush last item.
    if !current_fields.is_empty() {
        rows.push(current_fields);
    }

    if columns.is_empty() {
        return None;
    }

    // Build aligned rows.
    let mut data = FlatExportData::new(columns.clone());
    for fields in &rows {
        let mut row = vec![FieldValue::Null; columns.len()];
        for (key, val) in fields {
            if let Some(idx) = columns.iter().position(|c| c == key) {
                row[idx] = val.clone();
            }
        }
        data.add_row(row);
    }

    Some(data)
}

fn parse_yaml_kv(s: &str) -> Option<(String, FieldValue)> {
    let colon_pos = s.find(':')?;
    let key = s[..colon_pos].trim().to_string();
    let val_str = s[colon_pos + 1..].trim();

    let val = parse_yaml_value(val_str);
    Some((key, val))
}

fn parse_yaml_value(s: &str) -> FieldValue {
    if s.is_empty() || s == "~" || s == "null" {
        return FieldValue::Null;
    }
    if s == "true" {
        return FieldValue::Bool(true);
    }
    if s == "false" {
        return FieldValue::Bool(false);
    }

    // Quoted string.
    if s.starts_with('"') && s.ends_with('"') && s.len() >= 2 {
        let inner = &s[1..s.len() - 1];
        return FieldValue::Str(inner.replace("\\\"", "\"").replace("\\\\", "\\"));
    }

    // Array (color).
    if s.starts_with('[') && s.ends_with(']') {
        let inner = &s[1..s.len() - 1];
        let nums: Vec<f32> = inner
            .split(',')
            .filter_map(|n| n.trim().parse::<f32>().ok())
            .collect();
        if nums.len() == 4 {
            return FieldValue::Color([nums[0], nums[1], nums[2], nums[3]]);
        }
        return FieldValue::Str(s.to_string());
    }

    // Number.
    if let Ok(i) = s.parse::<i64>() {
        return FieldValue::Int(i);
    }
    if let Ok(f) = s.parse::<f64>() {
        return FieldValue::Float(f);
    }

    FieldValue::Str(s.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn round_trip_first(s: &str) -> FieldValue {
        let mut d = FlatExportData::new(vec!["v".into()]);
        d.add_row(vec![FieldValue::Str(s.into())]);
        let yaml = format_flat(&d);
        let parsed = parse_flat(&yaml).expect("parse");
        parsed.rows[0][0].clone()
    }

    fn round_trip_str(s: &str) -> String {
        match round_trip_first(s) {
            FieldValue::Str(out) => out,
            other => panic!("expected Str for {s:?}, got {other:?}"),
        }
    }

    #[test]
    fn type_confusable_strings_stay_strings() {
        // Regression: a `Str` payload that looks like a scalar of another
        // type must be quoted so it round-trips as a string, not an
        // Int/Float/Bool/Null.
        assert_eq!(round_trip_str("123"), "123");
        assert_eq!(round_trip_str("3.14"), "3.14");
        assert_eq!(round_trip_str("true"), "true");
        assert_eq!(round_trip_str("false"), "false");
        assert_eq!(round_trip_str("null"), "null");
        assert_eq!(round_trip_str("~"), "~");
    }

    #[test]
    fn indicator_leading_strings_stay_strings() {
        // Leading YAML indicators / structural chars must be quoted.
        assert_eq!(round_trip_str("- dash"), "- dash");
        assert_eq!(round_trip_str("[bracketish"), "[bracketish");
        assert_eq!(round_trip_str("@at"), "@at");
        assert_eq!(round_trip_str("key: value"), "key: value");
        assert_eq!(round_trip_str("has # hash"), "has # hash");
    }

    #[test]
    fn quoting_predicate_leaves_plain_words_bare() {
        // A plain word should NOT be quoted (keeps output readable).
        let mut d = FlatExportData::new(vec!["v".into()]);
        d.add_row(vec![FieldValue::Str("Alice".into())]);
        let yaml = format_flat(&d);
        assert!(yaml.contains("v: Alice"));
        assert!(!yaml.contains("\"Alice\""));
    }

    #[test]
    fn backslash_and_quote_escaping_round_trips() {
        assert_eq!(round_trip_str("a\\b"), "a\\b");
        assert_eq!(round_trip_str("a\"b"), "a\"b");
        assert_eq!(round_trip_str("a\\\"b"), "a\\\"b");
    }

    #[test]
    fn empty_string_round_trips() {
        assert_eq!(round_trip_str(""), "");
    }
}
